apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"creationTimestamp":"2022-12-22T18:46:24Z","generation":2,"labels":{"app":"feedback-api"},"name":"feedback-api","namespace":"default","resourceVersion":"360113","uid":"67df1f99-4462-449c-bed9-c6c4083b5762"},"spec":{"progressDeadlineSeconds":600,"replicas":2,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"feedback-api"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"feedback-api"}},"spec":{"containers":[{"image":"walidelass/feedback-api:submission","imagePullPolicy":"IfNotPresent","livenessProbe":{"httpGet":{"path":"/health","port":9000},"initialDelaySeconds":5,"periodSeconds":30},"name":"feedback-api","ports":[{"containerPort":80,"name":"feedback-api"}],"resources":{"limits":{"cpu":"130m","memory":"172Mi"},"requests":{"cpu":"130m","memory":"172Mi"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/app/Database/","name":"db-data"}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"volumes":[{"name":"db-data","persistentVolumeClaim":{"claimName":"sqlite-pvc"}}]}}},"status":{"conditions":[{"lastTransitionTime":"2022-12-22T18:46:24Z","lastUpdateTime":"2022-12-22T18:46:52Z","message":"ReplicaSet \"feedback-api-85d7d6565\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"},{"lastTransitionTime":"2022-12-22T18:58:04Z","lastUpdateTime":"2022-12-22T18:58:04Z","message":"Deployment does not have minimum availability.","reason":"MinimumReplicasUnavailable","status":"False","type":"Available"}],"observedGeneration":2,"replicas":2,"unavailableReplicas":2,"updatedReplicas":2}}
  creationTimestamp: "2022-12-22T22:20:42Z"
  generation: 1
  labels:
    app: feedback-api
  name: feedback-api
  namespace: default
  resourceVersion: "376173"
  uid: 521c9894-a2c0-4b04-914c-f79f3543b720
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: feedback-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: feedback-api
    spec:
      containers:
      - image: walidelass/feedback-api:submission
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        name: feedback-api
        ports:
        - containerPort: 80
          name: feedback-api
          protocol: TCP
        resources:
          limits:
            cpu: 130m
            memory: 172Mi
          requests:
            cpu: 130m
            memory: 172Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app/Database/
          name: db-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: sqlite-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: feedback-api-svc
spec:
  type: ClusterIP
  selector:
    app: api-gateway
  ports:
  - name: http
    port: 9000
    targetPort: 80
