apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"creationTimestamp":"2022-12-12T21:52:10Z","generation":1,"labels":{"app":"logic-api"},"name":"logic-api","namespace":"default","resourceVersion":"3052","uid":"1fb84e86-22fb-45bf-8b03-41b34a8cc388"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"logic-api"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"logic-api"}},"spec":{"containers":[{"image":"walidelass/logic-api:submission","imagePullPolicy":"IfNotPresent","name":"logic-api","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2022-12-12T21:52:47Z","lastUpdateTime":"2022-12-12T21:52:47Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2022-12-12T21:52:10Z","lastUpdateTime":"2022-12-12T21:52:47Z","message":"ReplicaSet \"logic-api-677f8784c4\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":1,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
  creationTimestamp: "2022-12-22T18:46:24Z"
  generation: 2
  labels:
    app: logic-api
  name: logic-api
  namespace: default
  resourceVersion: "359979"
  uid: 9cf18edf-5cfb-47c7-9f2d-cfcae62e21b9
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: logic-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: logic-api
    spec:
      containers:
      - image: walidelass/logic-api:submission
        imagePullPolicy: IfNotPresent
        name: logic-api
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 30
        resources: {}
        ports:
        - containerPort: 5000
          name: logic-api
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

---

apiVersion: v1
kind: Service
metadata:
  name: logic-api-svc
spec:
  type: ClusterIP
  selector:
    app: logic-api
  ports:
  - name: http
    port: 5000
    targetPort: 5000
