apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqlite-vol
  labels:
    type: local
spec:
  storageClassName: pv-scn
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"